services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: policlinico-app

    ports:
      - "8080:80"

    volumes:
      - .:/var/www/html
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf

    depends_on:
      - db

    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"


  db:
    image: mariadb:10.11

    container_name: policlinico-db

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: policlinico_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

    volumes:
      - policlinico_db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin

    container_name: policlinico-pma

    depends_on:
      - db

    ports:
      - "8081:80"

    environment:
      PMA_HOST: policlinico-db
      MYSQL_ROOT_PASSWORD: 123456


volumes:
  policlinico_db_data: